### ISSUE TITLE
QuoteQueryResponse seems to be missing "id" property

### ISSUE THREAD

**Issue by olegpetroveth** [chainflip-io/chainflip-sdk-monorepo#528]
SDK version 1.1.5

```typescript
type QuoteQueryResponse = {
    intermediateAmount?: string;
    egressAmount: string;
    includedFees: SwapFee[];
};
```

response received:
```json
{
  id: "a691563a-0547-43eb-8005-bb2b6822c64a",
  intermediateAmount: "2352187565",
  egressAmount: "5440084",
  includedFees: [
   // ...
  ],
}
```

Unless I missed something id property is missing and TS complains when trying to select that prop.

![image](https://github.com/chainflip-io/chainflip-sdk-monorepo/assets/90647190/7c865ed7-44f3-4ea4-83a8-f0fa84438da3)

**Comment by GabrielBuragev** [comment]
Just checked with the team and it seems like this `id` is only used internally and does not have any meaning to the outside. 
Are you trying to use it for something?
